title: Media Unmasked
permalink: /:categories/:title/
url: "http://mediaunmasked.com"
baseurl: ""
timezone: America/New_York
gems:
- jekyll-redirect-from
sass:
  sass_dir: assets/css/_sass
social_username: mediaunmasked