title: Media Unmasked
permalink: /:categories/:title/
url: "http://192.168.1.10:3000"
baseurl: ""
timezone: America/New_York
gems:
- jekyll-redirect-from
sass:
  sass_dir: assets/css/_sass
social_username: mediaunmasked
exclude: ['node_modules', '.sass-cache', '.gitignore', 'CNAME', 'gulpfile.js', '*.scss']